# Python-Learning

When I tried running the AAM_Utils2 module (which has a list of functions) including a variable summary function, an error occurred saying that there is an issue with "locale".
